apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: discoveryserver
  name: discoveryserver
  namespace: ecgc
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: discoveryserver
  template: 
    metadata: 
      labels: 
        app: discoveryserver
        name: discoveryserver-pod
      name: discoveryserver-pod
    spec: 
      containers: 
        - image: docker-registry.cdacmumbai.in:5000/discoveryserver.jar
          name: discoveryserver-pod
          ports:
            - containerPort: 8000
          
