apiVersion: v1
kind: Service
metadata:
  name: discoverserver-service
  namespace: ecgc
  labels:
    name: discoverserver-service
    app: discoveryserver
spec:
  type: ExternalName
  externalName: discoveryserver.ecgc
  ports:
  - port: 8000

      

