apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: discoveryserver
  name: hr-backend
  namespace: ecgc
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: discoveryserver
  template: 
    metadata: 
      labels: 
        app: discoveryserver
        name: hr-app-back-pod
      name: hr-app-back-pod
    spec: 
      containers: 
        - image: docker-registry.cdacmumbai.in:5000/hrd_emp_be.jar
          name: hr-app-back
          ports:
            - containerPort: 8001
          
