apiVersion: v1
kind: Service
metadata:
  name: hr-backend-service
  namespace: ecgcbackend
  labels:
    name: hr-backend-service
    app: discoveryserver
spec:
  selector:
    app: discoveryserver
  ports:
  - port: 8001
    targetPort: 8001
    
      

