apiVersion: v1
kind: Service
metadata:
  name: discoveryserver-service
  namespace: ecgc
  labels:
    name: discoveryserver-service
    app: discoveryserver
spec:
  selector:
    app: discoveryserver
  ports:
  - port: 8000
    targetPort: 8000
