apiVersion: v1
kind: Service
metadata:
  name: discoveryserver
  labels:
    name: discoverserver
    app: discoveryserver
spec:
  selector:
    app: discoveryserver
    name: discoveryserver-pod
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31223

